CREATE TABLE MATERIAS
	(
		SIGLAMATERIA CHAR(3) NOT NULL,
		NOMEMATERIA VARCHAR(50) NOT NULL,
		CARGAHORARIA FLOAT NOT NULL,
		SIGLACURSO CHAR(3) NOT NULL,
		IDPROFESSOR INT
			CONSTRAINT PK_MATERIA
			PRIMARY KEY (
							SIGLAMATERIA
							
						)
			CONSTRAINT FK_CURSO
			FOREIGN KEY (SIGLACURSO) REFERENCES CURSOS (SIGLACURSO),
		CONSTRAINT FK_PROFESSOR
			FOREIGN KEY (IDPROFESSOR)
			REFERENCES PROFESSOR (IDPROFESSOR)
	);