CREATE TABLE MATRICULA
	(
		IDMATRICULA INT,
		SIGLACURSO CHAR(3),
		SIGLAMATERIA CHAR(3),
		IDPROFESSOR INT,
		PERLETIVO INT,
		N1 FLOAT,
		N2 FLOAT,
		N3 FLOAT,
		N4 FLOAT,
		TOTALPONTOS FLOAT,
		MEDIA FLOAT,
		F1 INT,
		F2 INT,
		F3 INT,
		F4 INT,
		TOTALFALTAS INT,
		PERCFREQ FLOAT,
		RESULTADO VARCHAR(20),
		STATUSEXAME BIT , -- 0 para não exame , 1 para exame
		NOTAEXAME FLOAT,
		MEDIAFINAL FLOAT
			CONSTRAINT PK_MATRICULA
			PRIMARY KEY (
							IDMATRICULA,
							SIGLACURSO,
							SIGLAMATERIA,
							IDPROFESSOR,
							PERLETIVO
						),
		CONSTRAINT FK_ALUNOS_MATRICULA
			FOREIGN KEY (IDMATRICULA)
			REFERENCES ALUNOS (MATRICULA),
		CONSTRAINT FK_CURSOS_MATRICULA
			FOREIGN KEY (SIGLACURSO)
			REFERENCES CURSOS (SIGLACURSO),
		CONSTRAINT FK_MATERIAS FOREIGN KEY (SIGLAMATERIA) REFERENCES MATERIAS (SIGLAMATERIA),
		CONSTRAINT FK_PROFESSOR_MATRICULA
			FOREIGN KEY (IDPROFESSOR)
			REFERENCES PROFESSOR (IDPROFESSOR)
	);