-- PROCEDURES PARA TABELA ALUNOS

CREATE PROCEDURE procInsertAluno (
	@NOMEALUNO VARCHAR(50)
)AS BEGIN
INSERT ALUNOS(nome) VALUES (@NOMEALUNO)
END

CREATE PROCEDURE procSetAluno(
  @matricula int,
  @nomealuno varchar(50)
)
AS BEGIN
UPDATE ALUNOS SET nome = @nomealuno WHERE matricula = @matricula
END

-- PROCEDURES PARA TABELA CURSOS

CREATE PROCEDURE procInsertCursos(
	@SIGLACURSO CHAR(3),
  	@NOMECURSO VARCHAR(50)
)AS BEGIN
INSERT CURSOS(siglacurso,nomecurso) VALUES (@SIGLACURSO,@NOMECURSO)
END

CREATE PROCEDURE procSetNomeCursos(
  @SIGLACURSO CHAR(3),
  @NOMECURSO VARCHAR(50)
)
AS BEGIN
UPDATE CURSOS SET nomecurso = @NOMECURSO WHERE siglacurso = @SIGLACURSO
END

-- PROCEDURES PARA TABELA PROFESSOR

CREATE PROCEDURE procInsertProfessor(
  	@NOMEPROFESSOR VARCHAR(50)
)AS BEGIN
INSERT PROFESSOR(nomeprofessor) VALUES (@NOMEPROFESSOR)
END

CREATE PROCEDURE procSetProfessor(
  @idprofessor int,
  @nomeprofessor varchar(50)
)
AS BEGIN
UPDATE PROFESSOR SET nomeprofessor = @nomeprofessor WHERE idprofessor = @idprofessor
END

-- PROCEDURES PARA TABELA MATERIAS

CREATE PROCEDURE procInsertMaterias(
  @SIGLAMATERIA char(3),
  @NOMEMATERIA VARCHAR(50),
  @CARGAHORARIA FLOAT,
  @SIGLACURSO CHAR(3),
  @IDPROFESSOR INT
)AS BEGIN
INSERT INTO MATERIAS (SIGLAMATERIA, NOMEMATERIA, CARGAHORARIA, SIGLACURSO, IDPROFESSOR)
VALUES (@SIGLAMATERIA, @NOMEMATERIA, @CARGAHORARIA, @SIGLACURSO, @IDPROFESSOR)
END
GO

-- PROCEDURES PARA ROTINA DE CRIAR UM ALUNO E INSERIR DIRETAMENTE NUMA MATRICULA PARA CURSO ESPECIFICO
	
CREATE OR ALTER PROCEDURE RotinaAluno
(
    @nome varchar(50),
    @siglacurso char(3),
    @perletivo int
)
AS BEGIN
INSERT ALUNOS(NOME) VALUES (@nome)
INSERT MATRICULA (IDMATRICULA,SIGLAMATERIA,SIGLACURSO,IDPROFESSOR,PERLETIVO)
SELECT @@IDENTITY,SIGLAMATERIA,SIGLACURSO,IDPROFESSOR,@perletivo FROM MATERIAS WHERE SIGLACURSO = @siglacurso
END

-- PROCEDURES PARA CRIAR DADOS PADRÕES DO BANCO DE DADOS

CREATE OR ALTER PROCEDURE InsertDadosPadrao
AS BEGIN
	DECLARE
	@NOMEALUNO varchar(50),
	@NOMEPROFESSOR varchar(50),
	@SIGLACURSO char(3),
	@NOMECURSO varchar(50)
	
	SET @NOMEALUNO = 'Iago'
	SET @NOMEPROFESSOR = 'CaneloAlvarez'
	SET @SIGLACURSO = 'EDS'
	SET @NOMECURSO = 'Engenharia de Software'
	
	EXEC procInsertAluno @NOMEALUNO;
	
	EXEC procInsertCursos @SIGLACURSO,@NOMECURSO;
	
	EXEC procInsertProfessor @NOMEPROFESSOR;
END
